name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This is the crucial missing piece

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://uzairtechguide.github.io/
          sitemap-path: sitemap.xml
        # Add this line to hide internal files
          exclude: |
            **/components/**
            **/ind2.html
            **/aisgtest.html

      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Update sitemap.xml"
          file_pattern: sitemap.xml
