name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://uzairtechguide.github.io/
          sitemap-path: sitemap.xml
          add-lastmod: true

      - name: Cleanup sitemap (Manual Filter)
        run: |
          # Use sed to delete lines containing unwanted files
          sed -i '/components\//d' sitemap.xml
          sed -i '/ind2.html/d' sitemap.xml
          sed -i '/aisgtest.html/d' sitemap.xml
          sed -i '/googlebcc723c3e0ed51a2.html' sitemap.xml
        shell: bash

      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Cleaned sitemap.xml"
          file_pattern: sitemap.xml
